### ISSUE TITLE
Update authorization failed regarding changing the active key

### ISSUE THREAD

**Issue by GreenAces** [tarassh/fairy-wallet#71]
**MY SPECS**
fairy-wallet-0.10.0-x86_64.AppImage
ledger-live-1.1.11-x86_64.AppImage
ubuntu 16.04 LTS

Long story short. I have two hardware wallets that have two seperate eos accounts. I was checking out the new permissions feature for the fiary-wallet and decided to update my active key and it worked fine for hardware wallet (b) but when I tried to do the same thing on hardware wallet (a) I get the following error:

**ERROR MESSAGE**

name":"TransportStatusError"
"message":"Ledger device: Invalid data received (0x6a80)"
"stack":"Error at new TransportStatusError (/tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/@ledgerhq/hw-transport/lib/Transport.js:152:16) at TransportNodeHid._callee$ (/tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/@ledgerhq/hw-transport/lib/Transport.js:205:23) at tryCatch (/tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/regenerator-runtime/runtime.js:62:40) at Generator.invoke [as _invoke] (/tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/regenerator-runtime/runtime.js:296:22) at Generator.prototype.(anonymous function) [as next] (/tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/regenerator-runtime/runtime.js:114:21) at step (/tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30) at /tmp/.mount_fairy-5l4l0A/app/resources/app.asar/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13 at <anonymous>"
"statusCode":27264
"statusText":"INCORRECT_DATA"

**SIDE NOTE**
Hardware wallet (a) has my main eos holdings and I was just testing hardware wallet (b) to see how it would work. Everything worked flawlessly with hardware wallet (b). I created the account using EOS Vibes tool (https://eos-account-creator.com/choose/) and I chose NOT to create an active key since I knew I could change the permissions using the fairy wallet. Then I proceeded to update my active key using the fairy-wallet and everything worked just as expected. I try the same exact thing (except create a new account) on hardware wallet (a) and it was an epic fail updating the active key. What did do wrong? I generated my key pairs using scatter... haven't tried using any other tool...

Any thoughts or suggestions would be appreciated. Thanks in advance.

**Comment by tarassh** [comment]
So, you are getting an error on update permission for hw (a), Right?

**Comment by GreenAces** [comment]
Yes, I am getting an error for hardware wallet (a) only. 
I did not connect both devices at the same time.

**Comment by tarassh** [comment]
The error is related to update auth only?

**Comment by GreenAces** [comment]
I just tried sending a transaction using hardware wallet (a) and I didn't get any errors. Therefore that error is only produced when I try to change the active key. 

**Other things I tried:**
Using a different public key generated from scatter.
Using a different USB port.

Despite these other methods - I continue to get the same error.  

**SIDE NOTE**
I remember the first time I did this with hardware wallet (b) the fiary-wallet never prompted me to select active or owner when I tried changing the active key. Now it seems I have a choice to pick between the two. Nonetheless the end result is the same though. Even if I selected "update@active" or "update@owner" -- it would just produce that same error.

**Comment by sjhendriksz** [comment]
![2](https://user-images.githubusercontent.com/44939185/48956441-514b1800-ef53-11e8-89aa-948bf49c8415.PNG)

Unable to update permissions. Get the following message:
Ledger device: Invalid data received (0x6a80)
Status code 27264

**Comment by tarassh** [comment]
@GreenAces have you tried to change active key using https://eostoolkit.io/account/permissions

**Comment by GreenAces** [comment]
Hardware wallet(a) didn't have EOS firmware v1.1. Therefore I updated it and everything works as expected using the fairy wallet tool. Thanks for your support!
